import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Flex, Theme } from "@radix-ui/themes";
import { QCProvider } from "@/components/QCProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <QCProvider>
          <Theme appearance="dark" accentColor="red">
            <Flex className="h-screen" overflow={"hidden"} direction={"column"}>
              {children}
            </Flex>
          </Theme>
        </QCProvider>
      </body>
    </html>
  );
}
